### ISSUE TITLE
V15 - Unable to instantiate new UmbDocumentWorkspaceContext after upgrading from V14

### ISSUE THREAD

**Issue by kraftvaerk-chth** [umbraco/Umbraco-CMS#17693]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

We have some custom extension of the backoffice in a separate section outside of the Content section, where we instantiated a new UmbDocumentWorkspaceContext, in order to be able to render a list of `<umb-property-type-based-property>` in a custom view

Everything was working fine in V14, and we spent quite a bit of time working on a custom editing view for articles, but the code is breaking now after upgrading to V15

We need to create a new instance of the context and provide it from our custom code, since we can't consume it from another section where it doesn't exist already.

Since the export statement was changed to "export type" in the document package in this commit, we can no longer create a new instance of the context ourselves
https://github.com/umbraco/Umbraco.CMS.Backoffice/commit/d2fe0d223ac34ef14fa81d06220214cb2503a3a1#diff-fb5b477d0701a5c08bd5e0a6c235e00a7588b4fe9f708fbaa472563d6927939cR2

Is there another way we can create a new UmbDocumentWorkspaceContext, or somehow consume one outside of a document workspace?
If not, is there a reason why it has to be only a type export. or could it be changed back so we can instantiate the context ourselves again?

### Steps to reproduce

Create a new npm project with typescript and install @umbraco-cms/backoffice version "14.3.1"

Write some typescript code that imports and instantiates a new UmbDocumentWorkspaceContext like so:
```
import { UmbDocumentWorkspaceContext } from "@umbraco-cms/backoffice/document";

const context = new UmbDocumentWorkspaceContext(this);
```

Now upgrade the @umbraco-cms/backoffice package to "15.0.0", and you will see an error when trying to build using `tsc`
```
error TS1362: 'UmbDocumentWorkspaceContext' cannot be used as a value because it was exported using 'export type'.

24     readonly #documentWorkspaceContext = new UmbDocumentWorkspaceContext(this);
```

**Comment by nielslyngsoe** [comment]
Hi @kraftvaerk-chth 

Thanks for the issue, for those following along I will let you know that we had a chat about this case.

It is not ideal to spin up the Document Workspace Context on your own. Instead use the <umb-workspace> element to spin up a workspace where you like and use the Extension API to overwrite Workspace Views etc. for a custom experience.

I'm in touch with Kraftvaerk and if anything needs to be adjusted we are open for the inputs, but this specific matter should not be possible for now.
