### PR TITLE
Developer Experience: Improve cohost editor polyfill to work with dotnet watch (closes #22773)

### LINKED ISSUE #22773: `dotnet watch` breaks when editing cshtml files
### Which Umbraco version are you using?

17.3.5

### Bug summary

After upgrading to 17.3.5 hot reload using `dotnet watch` breaks whenever I update cshtml files.

I think it might have to do with #21861, as the message I get is this:

```
dotnet watch ⌚ File updated: .\Views\Home.cshtml
dotnet watch ⌚ No C# changes to apply.
dotnet watch ⚠ warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
System.ArgumentException: The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
-----

dotnet watch ⚠ warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
System.ArgumentException: The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
-----
```

### Specifics

I tried a fresh 17.3.5 install with The Starter Kit.

Removed the backofficedevelopment, generated models and enabled razor compilation.

Then whenever I start using `dotnet watch` it runs the site as expected. As soon as I edit a cshtml file, it breaks with the above message, and the frontend breaks:

Image

If I add this to my csproj it works...

```
  <ItemGroup>
    <AdditionalFiles Remove="**\*.cshtml" />
  </ItemGroup>
```

### Steps to reproduce

Enable RazorCompileOnBuild and RazorCompileOnPublish
Run with dotnet watch
Edit a cshtml file

The website breaks...

### Expected result / actual result

Expected to be able to use `dotnet watch` without problems (other than my own code problems :))

---
_This item has been added to our backlog AB#68088_

### PR DESCRIPTION
**Pull request by Migaroez**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Fixes #22773

### Description
This PR continues the work of https://github.com/umbraco/Umbraco-CMS/pull/21861 by improving the introduced polyfill to be compatible with the dotnet watch process. It does this by including the .cshtml in a way that does not collide with what the razor SDK does. More details can be found in the comments around the polyfill

### Things that were tested
- Initial fix allows vscode to debug cshtml files
- Initial fix makes the app crash when following reproduction steps in #22773
- Enhancement still allows vscode to debug cshtml files
- Enhacement makes it so the app does not crash when following reproduction steps in #22773

### Notes
This is far from my erea of expertise so I welcome any and all improvements to the proposed solution.
@davidwengier: if you have time, I would greatly appriciate if you could have a look at this one.

### CODE REVIEW

**Comment by davidwengier** [comment]
The comment seems reasonable, and the fix makes sense as a solution to the comment. It feels like a bit of a workaround for a deeper issue, but if it works, it works IMO.

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props [hunk 1]
```diff
@@ -21,16 +21,46 @@
...
+    item Identity (slash form / relative vs absolute) and the generator then sees two inputs that
+    derive the same hintName, which crashes it with CS8785 (see issue #22773).
+
+    Run as a target right before CoreCompile so the SDK's contribution is visible, then add only
+    the .cshtml files that are not already present. Both sides are normalized to %(FullPath) so
+    items with different Identity forms still compare equal.
+
+    Set EnableCohostEditorCompatibility=false in a project to opt out entirely.
+  -->
+  <Target Name="_UmbracoEnsureRazorAdditionalFilesForCohostEditor"
```
Comment (AndyButland) [inline src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]: Although this works here, by convention you'd expect it in the `Umbraco.Cms.Targets.targets` file.  Can you move it there and still see the fix working?

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props [hunk 2]
```diff
@@ -21,16 +21,46 @@
     only do them for design time builds, so that we don't impact regular builds or CI.
     We also have an escape hatch in case it does cause issues, users can set the appropriate property
```
Comment (AndyButland) [inline src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]:
```suggestion
    We also have an escape hatch in case it does cause issues, users can set EnableCohostEditorCompatibility=false
```

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props [hunk 3]
```diff
@@ -21,16 +21,46 @@
...
     in their project file to disable this.
+
+    CompilerVisibleProperty is read by the generator at initialization (before any target runs),
+    so it stays in an evaluation-time ItemGroup. It has no duplicate-entry problem.
```
Comment (AndyButland) [inline src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]:
```suggestion
    CompilerVisibleProperty is surfaced to generators via AnalyzerConfigOptionsProvider, not as a source-generator input file, 
    so it doesn't enter the hintName-collision codepath that AdditionalFiles does. Keeping it at evaluation time is safe.
```

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props
Comment (AndyButland) [inline src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]:
```suggestion
    The Razor editor in modern Visual Studio and the C# extension for VS Code use the Razor source generator
```

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props [hunk 4]
```diff
@@ -21,16 +21,46 @@
...
+    design-time builds they may not be present yet, which is what PR #21861 worked around.
+
+    Doing the include at evaluation time (as PR #21861 did) causes duplicates with the SDK during
+    dotnet watch / hot reload design-time builds: the SDK adds the same .cshtml under a different
+    item Identity (slash form / relative vs absolute) and the generator then sees two inputs that
+    derive the same hintName, which crashes it with CS8785 (see issue #22773).
+
+    Run as a target right before CoreCompile so the SDK's contribution is visible, then add only
+    the .cshtml files that are not already present. Both sides are normalized to %(FullPath) so
+    items with different Identity forms still compare equal.
```
Comment (AndyButland) [inline src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]:
```suggestion
    Run as a target before CoreCompile (hot-reload path) and CompileDesignTime (IDE design-time path) 
    so the SDK's contribution is visible in both cases. Then add only the .cshtml files that are not already 
    present. Both sides are normalized to %(FullPath) so items with different Identity forms still compare equal.
```

**Review by AndyButland — CHANGES_REQUESTED** [review]
Great work on finding a fix for the @Migaroez.  I've tested out with 17.4.1, can see the reported issue.  Then have taken the build from this PR and referenced it locally, and now see the expected behaviour.  I can edit `.cshtml` files, and see them refresh in the browser, and Intellisense still works.

Just had some comments on comments and a question about whether the fix is in the wrong file.  If you could look at those, then I think this is good to merge in (and we should consider for 17.5/18.0 given it's a regression when compared to an earlier 17 minor).

File: src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props (hunk 1 above)
Comment (Migaroez) [reply src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props]: Updated and still works.

**Review by AndyButland — APPROVED** [review]
Great.  Updates all look good to me and thanks for the confirmation that it continues to work as expected in the `.targets` file.

As mentioned I'll cherry-pick it over for 17.5 and 18.0.

**Comment by AndyButland** [comment]
Cherry-picked to `release/17.5.0` and `release/18.0` (and merged `v17/dev` up to `main`).
