### ISSUE TITLE
Backoffice Login not working with Safari 15 / umbraco 13.3.2

### ISSUE THREAD

**Issue by Tristan-Campbell** [umbraco/Umbraco-CMS#16639]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2

### Bug summary

The Umbraco BackOffice login screen does not work on older browsers. Testing on an iPad Air 2 (Safari 15) the Email and Password fields become unusable (no input can be added) and the Login button does not display. 

### Specifics

Javascript error is :
TypeError: this.attachInternals is not a function. (In 'this.attachInternals()', 'this.attachInternals' is undefined)

![Screenshot 2024-06-20 132858](https://github.com/umbraco/Umbraco-CMS/assets/25729265/3b993f6f-545c-4ab5-b877-6532e0a2f877)

### Steps to reproduce

Visit any v13.3.2 site at /umbraco/login with an older iPad such as iPad Air 2

**Comment by nul800sebastiaan** [comment]
Just to note: Umbraco 13 requires Safari 16.4+ (the error mentions `attachInternals`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals#browser_compatibility) 

When v13 was released the latest version of Safari was 17.2, so I'd recommend updating Safari first and see if that helps.

**Comment by nul800sebastiaan** [comment]
Just found that the Safari version depends on the iOS version, looks like all iPads released after 2016 should be able to get up to v16 at least, most to v17.

**Comment by Tristan-Campbell** [comment]
It might be worth adding a UI message to the login screen saying their device is not supported for these users rather than the UI being unresponsive which caused frustration. We've have a number of users who are stuck on older iPads which cannot be upgraded.

**Comment by nul800sebastiaan** [comment]
Sure, we'd love some help with that!

**Comment by ewuski** [comment]
The issue was happening to me on Safari on iPhone 11 v16... Once updated to 17.6.1 the problem has gone. The login works as expected now.

**Comment by awavevladimirmironov** [comment]
Yes. it would be great to have this message that this browser is not supported. I have the same issue at 13+  on mac. and Not oll of my client can have new MacOS. some have old version and safari 15.6.

**Comment by craigs100** [comment]
I'm having the same issue with an elderly, long term client and it's causing massive difficulties as she only has Apple devices.

**Comment by greystate** [comment]
We've just moved a site off Cloud and hit this bug with a client of ours. They didn't have any issues logging in with UmbracoID dialog (probably using real inputs?) but now they can't do anything.

I honestly don't understand why a login form can't start as two textboxes and a button and _then_ be enhanced in whatever way possible...

Early on (in UUI terms) there were a couple of really similar bugs, where a polyfill for the missing `.attachInternals()` was added to the project to make another form work (I think it was the Package Validation form?).

**Comment by AndyButland** [comment]
Good to hear.  I've checked internally and as you note we dp expect this to be resolved now due to the UUI update in 13.6.  I'll close this and label it now.
