### ISSUE TITLE
Blocklist label for media picker v3 property fails to load

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco-CMS#11139]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16

### Bug summary

When trying to get the name of a picked item using media picker v3 in a blocklist label it fails to load.

### Specifics

In the label field of my blocklist
Using this:
`My Block {{imageBlockImage[0].key | ncNodeName}}`
results in:
`My Block Loading...`
Forever and an error in the console:
`angular.js?cdv=1310148265:15635 Possibly unhandled rejection: {"errorMsg":"Failed to retrieve entity data for id 52add3b5-e565-4f54-ae74-0a57700630ea","data":"<html><body><h1>Page not found</h1><h3>No document matches the url '/umbraco/backoffice/UmbracoApi/Entity/GetById?id=52add3b5-e565-4f54-ae74-0a57700630ea&amp;type=Document'</h3><p>This page can be replaced with a custom 404. Check the documentation for \"custom 404\".</p><p style=\"border - top: 1px solid #ccc; padding-top: 10px\"><small>This page is intentionally left ugly ;-)</small></p></body></html>","status":404}`
It seems like it adds type=Document automatically in the request.

Using this:
`My Block {{imageBlockImage[0] | ncNodeName}}`
results in:
`angular.js?cdv=1310148265:15635 Error: [$interpolate:interr] Can't interpolate: My Block {{imageBlockImage[0] | ncNodeName}}
TypeError: input.split is not a function`

Using this:
`My Block {{imageBlockImage | ncNodeName}}`
results in:
`angular.js?cdv=1310148265:15635 Error: [$interpolate:interr] Can't interpolate: My Block {{imageBlockImage | ncNodeName}}
TypeError: input.split is not a function`

The blocklist docs don't say anything specific about displaying image names. So I've been referring to forum posts and the nested content docs. 

If I switch the property to a v2 media picker this works:
`{{imageBlockImage | ncNodeName}}`

### Steps to reproduce

Install Umbraco v8.16
create a blocklist containing elements with a media picker v3 property
format the label using ncNodeName

### Expected result / actual result

Expected:
The label displays the name of the media item.

Actual:
The label fails to load, and an error is thrown in the console.

**Comment by nul800sebastiaan** [comment]
Thanks @krebil - I've had a look and I am not quite sure what I'm doing but it turns out something like this is working:

```javascript
Feature {{imageBlockImage && imageBlockImage[0] ? ('umb://media/' + imageBlockImage[0].mediaKey | ncNodeName) : ''}}
````

The here is to use `mediaKey` instead of the `key`, not sure what the key is for MediaPicker3.

I've also made it "safe", so checking if an `imageBlockImage` exists first and then if there's at least one of them selected. I hope this helps. I'll check at HQ if we can help make this easier.

**Comment by krebil** [comment]
Thanks for the workaround @nul800sebastiaan
Unfortunately, I haven't had time to try it out until today. And I have since updated to 8.17.
In my project, your solution does not work. It does remove the error from the console. But it's stuck at 'loading..'
In the network tab, I can see the request to getById and the response body, the content seems fine.

Testing with a content picker works as expected.
Testing with media v2 also results in loading indefinitely

Not sure if this is related to the 8.17 update or not.

**Comment by kfr-dwarf** [comment]
@nul800sebastiaan 
Had this issue on V8.18.0 and tried out your workaround, but I'm still stuck on "loading...". Saving or Publishing the page will temporarily fix the issue and show the name of the image I've selected in my mediapicker, but once I refresh the page, I am back to being stuck on loading. I can see this issue has been closed, but is there another issue I can follow to track the progress on this feature?

**Comment by krebil** [comment]
@kfr-dwarf 
So for me, it was a performance issue. Sometimes it wouldn't show up but after a few refreshes, it would. I eventually had to abandon it because it became too unstable when using nested blocklists
I've noticed that the blocklist fetches GetEmptyByKeys for every blocklist item and I think there is another fetch whenever you use ncNodeName. 

This is loading a content node in one of my recent projects
![image](https://user-images.githubusercontent.com/1363512/156170463-5cd50551-e736-42a3-84ef-8e659ba99c58.png)

You can also check out this issue: https://github.com/umbraco/Umbraco-CMS/issues/10127

https://github.com/umbraco/Umbraco-CMS/issues/10127#issuecomment-820992069

This commenter made the same conclusion as me, however, the thread isn't long and has no workaround and the issue is still open.

**Comment by Myster** [comment]
This is still broken in umbraco 9.4.3
I can't do this:
`{{image  | ncNodeName}}`
this work-around does work:
`{{image && image[0] ? ('umb://media/' + image[0].mediaKey | ncNodeName) : ''}}`
