### ISSUE TITLE
`dotnet watch` breaks when editing cshtml files

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#22773]
### Which Umbraco version are you using?

17.3.5

### Bug summary

After upgrading to 17.3.5 hot reload using `dotnet watch` breaks whenever I update cshtml files.

I think it might have to do with #21861, as the message I get is this:

```
dotnet watch ⌚ File updated: .\Views\Home.cshtml
dotnet watch ⌚ No C# changes to apply.
dotnet watch ⚠ warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
System.ArgumentException: The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
-----

dotnet watch ⚠ warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
System.ArgumentException: The hintName 'Views_Partials_Components_LatestBlogPosts_NoContent_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
-----
```

### Specifics

I tried a fresh 17.3.5 install with The Starter Kit.

Removed the backofficedevelopment, generated models and enabled razor compilation.

Then whenever I start using `dotnet watch` it runs the site as expected. As soon as I edit a cshtml file, it breaks with the above message, and the frontend breaks:

<img width="2560" height="1271" alt="Image" src="https://github.com/user-attachments/assets/34a3eb83-af6b-4860-8389-327941f082ec" />

If I add this to my csproj it works...

```
  <ItemGroup>
    <AdditionalFiles Remove="**\*.cshtml" />
  </ItemGroup>
```

### Steps to reproduce

Enable RazorCompileOnBuild and RazorCompileOnPublish
Run with dotnet watch
Edit a cshtml file

The website breaks...

### Expected result / actual result

Expected to be able to use `dotnet watch` without problems (other than my own code problems :))

---
_This item has been added to our backlog AB#68088_

**Comment by AndyButland** [comment]
Fixed via https://github.com/umbraco/Umbraco-CMS/pull/22999 for 17.5 and 18.0 (will be part of 18.0-rc2).
